# Force Gradle to use Temurin 21 and ignore others

org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=C\:/Users/ADMIN/scoop/apps/temurin21-jdk/current
org.gradle.java.installations.include-jres=false

# Android & Kotlin Settings
android.useAndroidX=true
android.nonTransitiveRClass=true
android.experimental.sdk.includeJdkImage=false
android.jdk.includeJdkImage=false
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
